[github_app]
pr_commands = [
    "/describe",
    "/review",
    "/review auto_approve",
    "/improve",
]

[config]
enable_auto_approval = true  # For criteria-based auto-approval
enable_comment_approval = true  # For approval via comments

[pr_description]
publish_labels=true
publish_description_as_comment=true
generate_ai_title=true
final_update_message=true

[pr_reviewer]
enable_review_labels_effort = true
enable_review_labels_security = true
inline_code_comments=false
require_score_review=true
require_can_be_split_review=true
require_estimate_effort_to_review=true
require_tests_review=true
require_security_review=true
extra_instructions="""
Review this project with the following key points in mind:
1. PHP Compatibility: This library supports PHP versions 5.6 to 8.3, including EOL versions. Code must be compatible with PHP 5.6.
2. Purpose: testcontainers-php manages Docker containers for PHP test environments, providing consistent and isolated test dependencies.
3. Design Principles: 
   - Minimal dependencies (mainly symfony/process and psr/log)
   - Trait-based composition for container settings
   - Type-safe value objects for domain concepts
4. Coding Standards:
   - Use PHPDoc for type information (not type declarations for PHP 5.6 compatibility)
   - Follow K&R style bracing (braces on same line)
   - Use 4-space indentation
   - Prefer fluent interfaces and method chaining
5. Error Handling: Ensure proper exception handling and resource cleanup
"""

[pr_code_suggestions]
focus_only_on_problems=true
num_code_suggestions_per_chunk="3"
commitatable_code_suggestions=false

[best_practices]
enable_global_best_practices = true
